entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ivan@epifront.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
